#!/bin/sh
export PATH=/usr/local/mysql/bin:$PATH
cat > /etc/my.cnf <<EOF
[mysqld]
server-id=1
log-bin=mysql-bin
[client]
user=root
EOF
chown root: /etc/my.cnf
chmod 644 /etc/my.cnf
invoke-rc.d mysql restart
mysql -e "GRANT ALL ON *.* TO 'root'@'192.168.2.2' IDENTIFIED BY 'rootpass'"
mysql -e "GRANT REPLICATION SLAVE ON *.* TO 'slave'@'192.168.2.2' IDENTIFIED BY 'slavepass'"
mysql -e "DROP DATABASE IF EXISTS world"

mysqladmin ping
exit $?
